[build]
builder = "NIXPACKS"
buildCommand = "bun install"

[deploy]
startCommand = "bun run index.ts"
healthcheckPath = "/api/clicks"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3